# Generated by Django 3.2.8 on 2021-10-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=154)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('bio', models.CharField(max_length=200)),
            ],
        ),
    ]
